Add cargo-auditable config option
axodotdev/cargo-dist pull request #1528
Opened 2024-11-05 20:34 UTC by duckinator

deferred:
- local auto-installation of cargo-auditable (moved to #1527)
- throw error when using cargo-auditable=true with non-rust projects (moved to #1526)

complete:
- [x] use `cargo auditable build` instead of `cargo build` if `cargo-auditable=true`
- [x] install cargo-auditable in workflows if `cargo-auditable=true`
- [x] tests for both of those
- [x] real-world local test
- [ ] real-world CI test

Moved from #1516 because the `duckinator/auditable-builds` branch name was incompatible with testing dist from a GitHub branch.

2024-11-05 21:11 UTC, mistydemeo requested changes
Realized there's one mistake in the template setup - something needs to get moved.

2024-11-05 21:11 UTC, mistydemeo commented on cargo-dist/templates/ci/github/release.yml.j2
> +      - name: Install cargo-auditable
Hm, I realized we're putting this in the wrong place. This is before `plan`, which plans out the job but doesn't actually perform the builds. What we actually want to do here is have `cargo auditable` installed for the local builds, which is the area starting L178 in this file.

You'll want to ensure that the github matrix entry which has the `install_dist` key gets a new `install_cargo_auditable` key, and that that gets assigned with a platform-appropriate value the same way it gets assigned for dist.

2024-11-05 23:57 UTC, duckinator commented
```
$ cargo audit bin axolotlsay                                                                                                              
    Fetching advisory database from `https://github.com/RustSec/advisory-db.git`
      Loaded 664 security advisories (from /home/puppy/.cargo/advisory-db)
    Updating crates.io index
       Found 'cargo auditable' data in axolotlsay (23 dependencies)
```

2024-11-06 00:04 UTC, mistydemeo approved these changes
One minor, non-blocking comment. Otherwise, I think we're looking great here! The snapshot tests show the changes we'd want to see in the outputs, too.

2024-11-06 00:04 UTC, mistydemeo commented on cargo-dist/src/backend/ci/github.rs
> +    pub install_cargo_auditable_ps1: String,
I believe we can drop these two fields since we're exclusively installing it via the GitHub matrix now?

2024-11-06 00:10 UTC, merged