fix(generate): provide a warning if something is skipped
axodotdev/cargo-dist pull request #415
Opened 2023-09-07 23:42 UTC by mistydemeo

In testing, I found it too easy to miss that `generate` was skipping generation; a printed warning makes that clearer.

2023-09-11 19:46 UTC, Gankra requested changes
i'm very confused by this implementation, which seems to make it so:

* if you run `cargo dist generate ci --allow-dirty` we always produce an error (reasonable, it's a no-op)
* if you run `cargo dist generate --allow-dirty` it's still a no-op but we don't complain
* if you run `cargo dist generate ci` with `allow-dirty = ["ci"]` we will warn
* if you run `cargo dist generate` with `allow-dirty = ["ci"]` we don't say anything

Presumably if you want to warn about skips you want to do it in the next loop (and only do it if there was actually something selected to be generated..?)

2023-09-11 19:48 UTC, Gankra commented
ohh i guess there's complication around --check vs not and commands implicitly invoking this..?

2023-09-11 20:24 UTC, mistydemeo commented
> ohh i guess there's complication around --check vs not and commands implicitly invoking this..?

Yeahhhh, that's right.

> if you run cargo dist generate ci with allow-dirty = ["ci"] we will warn
> if you run cargo dist generate with allow-dirty = ["ci"] we don't say anything

Now that I think about it this really should be backwards, even though I did put it in the explicitly-specified mode. Handling it on the inferred side probably makes more sense rather than just being silent.

2023-10-23 16:37 UTC, ashleygwilliams commented
there's some conflicts here and the longer we wait the more we'll run into- what are we thinking about this PR generally?

2023-10-30 17:48 UTC, closed without merging

2023-10-30 17:48 UTC, mistydemeo commented
I don't really care as much about this now. If we get complaints from users we can revisit.