Add support for Linuxbrew
axodotdev/cargo-dist pull request #561
Opened 2023-11-10 18:42 UTC by dsully

First pass at adding Linuxbrew support.

Use `on_macos`/`on_linux` and `on_arm`/`on_intel` as Homebrew stanzas instead of `Hardware::CPU.type`

Update insta snaps.

Fixes #501

2023-11-15 01:05 UTC, mistydemeo reviewed
Thank you very much! I'll do a more thorough review tomorrow, but I really appreciate the contribution.

2023-11-15 22:44 UTC, mistydemeo requested changes
Looks good, thank you! Just a few minor comments.

Again, I really appreciate the contribution.

2023-11-15 22:44 UTC, mistydemeo commented on cargo-dist/src/tasks.rs
> +        // to try to install x64 on arm64 and let Rosetta2 deal with it.
If we're going to change the formatting of these, let's use the official spelling here and elsewhere in the file.
```suggestion
        // to try to install x64 on arm64 and let Rosetta 2 deal with it.
```

2023-11-15 22:44 UTC, mistydemeo commented on cargo-dist/templates/installer/homebrew.rb.j2
> +    on_arm
This needs a `do` as part of the block.

```suggestion
    on_arm do
```

2023-11-15 22:44 UTC, mistydemeo commented on cargo-dist/templates/installer/homebrew.rb.j2
> +    on_intel
Likewise.

```suggestion
    on_intel do
```

2023-11-17 04:23 UTC, dsully commented
Thanks for catching those missing `do` statements. Updated along with the name fixes.

2023-11-20 19:14 UTC, mistydemeo reviewed
Looks good, thank you!

We're cutting a new release soon, so I'll get this merged after that. Do you mind rebasing on `main` and updating the test fixtures with the template change you made in the last commit?

2023-11-20 23:09 UTC, dsully commented
Done, just pushed another commit.

2023-11-21 00:38 UTC, mistydemeo approved these changes
Great, thank you! I'll get this merged after 0.5.0 is released.

2023-11-27 19:10 UTC, merged

2023-11-27 19:11 UTC, mistydemeo commented
Thanks again! We'll include this in a future release, most likely 0.6.0.